// imports the react-dom/client library
import { DataTypes, Sequelize, Model, Optional } from 'sequelize';

// defines the attributes of the car object
interface CarAttributes {
  id: number;
  make: string;
  model: string;
  year: number;
  price: number;
}

// extends the car attributes but makes id optional useful when creating new instances where id is auto generated by database
interface CarCreationAttributes extends Optional<CarAttributes, 'id'> {}

// The properties are marked with the !.  This operator will be assigned a value at runtime.
// By extending the carr class gains all the methods of the model class & enforces the structure defined by CarAttributes and 
// CarCreationAttributes.  This setup insures type safety and consistency when working with Car instances in the app.
export class Car extends Model<CarAttributes, CarCreationAttributes> implements CarAttributes {
  public id!: number;
  public make!: string;
  public model!: string;
  public year!: number;
  public price!: number;
}

// CarFactory function that takes in sequelize and returns the Car model
// This allows for the interaction of the car table in the database
export function CarFactory(sequelize: Sequelize): typeof Car {
  Car.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      make: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      model: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      year: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      price: {
        type: DataTypes.FLOAT,
        allowNull: false,
      },
    },
    {
      tableName: 'Car',
      sequelize,
    }
  );


  return Car;
}
