//must install required packages
//npm install react-router-dom
//npm install @types/react-router-dom
//npm install @types/react
import { DataTypes, Sequelize, Model, Optional } from 'sequelize';

// imported from local file car.js
import { Car } from './car.js';

// defines the attributes of the work object 
interface WorkAttributes {
  id: number;
  name: string;
  status: string;
  description: string;
  assignedCarId?: number;
}

//extends the work attributes but makes id optional useful when creating new instances where id is auto generated by database
interface WorkCreationAttributes extends Optional<WorkAttributes, 'id'> {}

export class Work extends Model<WorkAttributes, WorkCreationAttributes> implements WorkAttributes {
  public id!: number;
  public name!: string;
  public status!: string;
  public description!: string;
  public assignedCarId!: number;

  // associated Car model
  public readonly assignedCar?: Car;
}

// WorkFactory function that takes in sequelize and returns the Work model
//The sequelize instance is passed to associate the model with a specific database connection
// the function returns the initialized Work model
export function WorkFactory(sequelize: Sequelize): typeof Work {
  Work.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      status: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      description: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      assignedCarId: {
        type: DataTypes.INTEGER,
        allowNull: true,
      },
    },
    {
      tableName: 'work',
      sequelize,
    }
  );

  return Work;
}
